
version: "3"

services:
  redis:
    image: redis
    # ports:
    #   - 6379:6379 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      retries: 10
    deploy:
      restart_policy:
        condition: any
  httr:
    privileged: true
    build:
      context: .
    env_file:
      - httr_settings.env
