library(BiocManager)
BiocManager::install(version = "3.19", update = F, ask = F)
remove.packages('RcppEigen')
BiocManager::install('DESeq2',ask=FALSE)
if (packageVersion('DESeq2') == '1.44.0') print("DESeq2 VERSION IS 1.44.0 !") else print("PROBLEM: DESeq2 VERSION IS NOT 1.44.0 !")
