install.packages("jsonlite",dependencies=TRUE,repos='http://cran.r-project.org/')
install.packages("mongolite",dependencies=TRUE,repos='http://cran.r-project.org/')
install.packages("data.table",dependencies=TRUE,repos='http://cran.r-project.org/')
install.packages("doParallel",dependencies=TRUE,repos='http://cran.r-project.org/')
install.packages("foreach",dependencies=TRUE,repos='http://cran.r-project.org/')